### ISSUE TITLE
Unavailable values should not be drawn

### ISSUE THREAD

**Issue by caruccio** [viniciusdacal/getup-charts#5]
Missing or null points in the interval (avg=null, for instance) must be omited from the graph.

Examples:

![captura de tela 2016-10-11 as 13 56 51](https://cloud.githubusercontent.com/assets/540936/19280243/3b9237a4-8fbb-11e6-814a-f07679e9966d.png)
![captura de tela 2016-10-11 as 13 50 14](https://cloud.githubusercontent.com/assets/540936/19280242/3b8723b4-8fbb-11e6-9660-d046f7bcb4ff.png)

**Comment by viniciusdacal** [comment]
closed by #8
